services:

  # ====================================================
  #                HASHICORP VAULT
  # ====================================================

  vault-prod:
    image: hashicorp/vault:1.21.1
    container_name: vault-prod
    restart: always
    expose:
      - "8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  vault-init-prod:
    image: hashicorp/vault:1.21.1
    container_name: vault-init-prod
    restart: on-failure
    depends_on:
      - vault-prod
    volumes:
      - ./Security/HashicorpVault/hashicorpVault.init.sh:/hashicorpVault.init.sh
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - JWT_SECRET_VALUE=${JWT_SECRET_VALUE}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - INTRA_CLIENT_ID=${INTRA_CLIENT_ID}
      - INTRA_CLIENT_SECRET=${INTRA_CLIENT_SECRET}
      - AUTH_SERVICE_TOKEN=${AUTH_SERVICE_TOKEN}
      - USER_SERVICE_TOKEN=${USER_SERVICE_TOKEN}
      - GLOBAL_CHAT_SERVICE_TOKEN=${GLOBAL_CHAT_SERVICE_TOKEN}
      - PRIVATE_CHAT_SERVICE_TOKEN=${PRIVATE_CHAT_SERVICE_TOKEN}
      - PONG_SERVICE_TOKEN=${PONG_SERVICE_TOKEN}
    entrypoint: /hashicorpVault.init.sh
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  # ====================================================
  #         APPLICATION MICROSERVICES (GHCR)
  # ====================================================

  auth-service-prod:
    image: ghcr.io/olaaroub/transcendence/auth-service:latest
    container_name: auth-service-prod
    restart: always
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully
    expose:
      - "3001"
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${AUTH_SECRET_PATH}
      - AUTH_SERVICE_TOKEN=${AUTH_SERVICE_TOKEN}
      - DATABASE_PATH=/data/auth.db
      - HOST=0.0.0.0
      - DOMAIN=${AUTH_DOMAIN}
      - SERVICE_EXT=-prod
      - LOG_LEVEL=info
    user: root
    volumes:
      - ./db/auth:/data
      - ./static:/app/static
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  user-service-prod:
    image: ghcr.io/olaaroub/transcendence/user-service:latest
    container_name: user-service-prod
    restart: always
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully
    expose:
      - "3002"
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${USER_SECRET_PATH}
      - USER_SERVICE_TOKEN=${USER_SERVICE_TOKEN}
      - DATABASE_PATH=/data/users.db
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=info
    user: root
    volumes:
      - ./db/users:/data
      - ./static:/app/static
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  global-chat-prod:
    image: ghcr.io/olaaroub/transcendence/global-chat:latest
    container_name: global-chat-prod
    restart: always
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully
    expose:
      - "3003"
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${GLOBAL_CHAT_SECRET_PATH}
      - GLOBAL_CHAT_SERVICE_TOKEN=${GLOBAL_CHAT_SERVICE_TOKEN}
      - DATABASE_PATH=/data/global.db
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=info
    user: root
    volumes:
      - ./db/chat:/data
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  private-chat-prod:
    image: ghcr.io/olaaroub/transcendence/private-chat:latest
    container_name: private-chat-prod
    restart: always
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully
    expose:
      - "3004"
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${PRIVATE_CHAT_SECRET_PATH}
      - PRIVATE_CHAT_SERVICE_TOKEN=${PRIVATE_CHAT_SERVICE_TOKEN}
      - DATABASE_PATH=/data/private.db
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=info
    user: root
    volumes:
      - ./db/chat:/data
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  pong-game-prod:
    image: ghcr.io/olaaroub/transcendence/pong-game:latest
    container_name: pong-game-prod
    restart: always
    depends_on:
      vault-init-prod:
        condition: service_completed_successfully
    expose:
      - "3005"
    environment:
      - VAULT_ADDR=${VAULT_ADDR_PROD}
      - VAULT_SECRET_PATH=${PONG_SECRET_PATH}
      - PONG_SERVICE_TOKEN=${PONG_SERVICE_TOKEN}
      - HOST=0.0.0.0
      - SERVICE_EXT=-prod
      - LOG_LEVEL=info
    user: root
    volumes:
      - pong-dist:/pong-dist
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  # ====================================================
  #     MODSECURITY CRS/API GATEWAY & FRONTEND
  # ====================================================

  modSecurity-prod:
    image: owasp/modsecurity-crs:4.21.0-nginx-alpine-202512071012
    container_name: modSecurity-prod
    restart: always
    depends_on:
      - auth-service-prod
      - user-service-prod
      - global-chat-prod
      - private-chat-prod
      - pong-game-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MODSEC_RULE_ENGINE=on
      - BLOCKING_PARANOIA=2
    volumes:
      - ./Security/ModSecurity/nginx.conf:/etc/nginx/templates/conf.d/default.conf.template:ro
      - ./Security/ModSecurity/rules/exceptions.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-CUSTOM-EXCLUSIONS.conf:ro
      - ./Security/ModSecurity/scanContent.sh:/usr/local/bin/scanContent.sh:ro
      - ./Security/ModSecurity/gateway_logs.conf:/etc/nginx/conf.d/00_logging.conf:ro
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  frontend-prod:
    image: ghcr.io/olaaroub/transcendence/frontend:latest
    container_name: frontend-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    depends_on:
      - modSecurity-prod
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./Security/ModSecurity/frontend_logs.conf:/etc/nginx/conf.d/00_logging.conf:ro
      - pong-dist:/app/assets/game:ro
    environment:
      - SERVICE_EXT=-prod
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  # ====================================================
  #        METRICS PROMETHEUS / GRAFANA
  # ====================================================

  prometheus-prod:
    image: prom/prometheus:v3.8.1
    container_name: prometheus-prod
    restart: always
    expose:
      - "9090"
    depends_on:
      - auth-service-prod
      - user-service-prod
      - global-chat-prod
      - private-chat-prod
      - pong-game-prod
    volumes:
      - ./Metrics/prometheus/prometheus.prod.yaml:/etc/prometheus/prometheus.yml:ro
      - ./Metrics/prometheus/alertRules.yaml:/etc/prometheus/alertRules.yaml:ro
      - prometheus-data:/prometheus
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

  grafana-prod:
    image: grafana/grafana:12.3.0
    container_name: grafana-prod
    restart: always
    expose:
      - "3000"
    depends_on:
      - prometheus-prod
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Metrics/grafana/provisioning:/etc/grafana/provisioning
      - ./Metrics/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - transcendence-deploy-net
      - transcendence-shared-net

networks:
  transcendence-deploy-net:
    name: transcendence-deploy-net
    driver: bridge
  transcendence-shared-net:
    external: true

volumes:
  prometheus-data:
    driver: local
  vault-data:
    driver: local
  grafana-data:
    driver: local
  pong-dist:
    driver: local