{
 "title": "User Insights",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chat messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\"rate(chat_messages_sent_total[5m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Friendships Added / Blocked (per hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(user_friendship_actions_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User growth chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "app_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_total", "legendFormat": "__auto" }
   ]
  }
 ]
}