{
 "title": "Fastify Metrics (Provisioned)",
 "description": "Nodejs runtime metrics for Fastify",
 "tags": [
  "fastify",
  "nodejs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h"
   },
   {
    "name": "service",
    "query": "label_values(nodejs_version_info, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{service=~\"$service\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{service=~\"$service\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_active_handles{service=~\"$service\"}",
     "legendFormat": "{{service}} {{type}}"
    },
    {
     "expr": "nodejs_active_handles_total{service=~\"$service\"}",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "Metrics scrape duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Process Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "% CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$service\"}[$interval])",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{service=~\"$service\"}",
     "legendFormat": "{{service}} Lag"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{service=~\"$service\"})*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Max file descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Failed Login Attempts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_login_attempts_total{status=\"failure\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}} Resident"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "External Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}} External"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}} Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}} Used"
    }
   ]
  },
  { "title": "Heap Space Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}}-{{space}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{service=~\"$service\"}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  }
 ]
}