{
 "title": "User Insights",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logging attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "auth_login_attempts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User searchs counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_searches_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Friendships Accepted / Blocked",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_friendship_actions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chat messages (global/private)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chat_message_sent_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User growth chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "app_users_total", "legendFormat": "__auto" }
   ]
  }
 ]
}