FROM node:20-alpine

WORKDIR /app

COPY . .

WORKDIR /app/Shared
RUN npm install && npm run build

WORKDIR /app/Offline
RUN npm install
RUN npm run build -- --base=/game/

FROM nginx:alpine

COPY --from=0 /app/Offline/dist /usr/share/nginx/html/game

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]